I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/script.rpy", line 6, in script call
    call variable
  File "game/script.rpy", line 15, in script
    $ visit[30] = False
  File "game/script.rpy", line 15, in <module>
    $ visit[30] = False
NameError: name 'visit' is not defined

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/script.rpy", line 6, in script call
    call variable
  File "game/script.rpy", line 15, in script
    $ visit[30] = False
  File "renpy/ast.py", line 928, in execute
    renpy.python.py_exec_bytecode(self.code.bytecode, self.hide, store=self.store)
  File "renpy/python.py", line 2245, in py_exec_bytecode
    exec(bytecode, globals, locals)
  File "game/script.rpy", line 15, in <module>
    $ visit[30] = False
NameError: name 'visit' is not defined

Windows-10-10.0.19041
Ren'Py 7.4.11.2266
TestYou 1.0
Wed Jan 19 14:12:09 2022
